<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="Dharuns-MacBook-Pro.local" name="com.FantasySpin.test.Settings" tests="11" failures="0" timestamp="12 Jan 2021 09:14:23 GMT" time="34.046" errors="2">
  <testcase name="LaunchApp" time="34.018" classname="com.FantasySpin.test.Settings"/>
  <testcase name="teardown" time="0.000" classname="com.FantasySpin.test.Settings">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.FantasySpin.report.ExtentReport.teardown(ExtentReport.java:145)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- teardown -->
  <testcase name="tearDown" time="0.028" classname="com.FantasySpin.test.Settings">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.FantasySpin.report.ExtentReport.getScreenshot(ExtentReport.java:193)
at com.FantasySpin.report.Base.tearDown(Base.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase name="ValidCredentials" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- ValidCredentials -->
  <testcase name="LoginScreen" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- LoginScreen -->
  <testcase name="SettingsTab" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- SettingsTab -->
  <testcase name="HowtoPlay" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- HowtoPlay -->
  <testcase name="Scorings" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- Scorings -->
  <testcase name="FrequentlyAskedQuestions" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- FrequentlyAskedQuestions -->
  <testcase name="LegalAndSupport" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- LegalAndSupport -->
  <testcase name="Feedback" time="0.000" classname="com.FantasySpin.test.Settings">
    <skipped/>
  </testcase> <!-- Feedback -->
</testsuite> <!-- com.FantasySpin.test.Settings -->
